const ActionTypes = {
    INCREMENT: 'INCREMENT',
    SET_INCREMENT: 'SET_INCREMENT',
    DECREMENT: 'DECREMENT',
    SET_DECREMENT: 'SET_DECREMENT',

    GET_RESPONSE: 'GET_RESPONSE',
    SET_RESPONSE: 'SET_RESPONSE',

    RESET_STATE: 'RESET_STATE',
} as const;

export default ActionTypes;
